@echo off
echo 🚀 Starting Edufirst Backend...
cd backend
if not exist node_modules (
    echo 📦 Installing dependencies...
    npm install
)
echo 🗄️ Generating Prisma client...
npm run prisma:generate
if not exist prisma\dev.db (
    echo 🗃️ Running migrations...
    npm run prisma:migrate:dev -- --name init
    echo 🌱 Seeding database...
    npm run prisma:seed
)
echo ⚡ Starting development server...
npm run start:dev